/* DO NOT EDIT THIS FILE
 * Automatically generated by generate-def-headers.xsl
 * DO NOT EDIT THIS FILE
 */

#ifndef __BFIN_DEF_ADSP_EDN_core__
#define __BFIN_DEF_ADSP_EDN_core__


#define SRAM_BASE_ADDR         0x1FC00000         /* L1DM SRAM Base Address Register */
#define DMEM_CONTROL           0x1FC00004         /* L1DM Data Memory Control Register */
#define DMEM_STAT              0x1FC00008         /* L1DM Data Memory CPLB Status Register */
#define DCPLB_FAULT_STATUS     0x1FC00008         /*     Older definition or alias of above */
#define DCPLB_FAULT_ADDR       0x1FC0000C         /* L1DM Data Memory CPLB Fault Address Register */
#define DCPLB_DFLT             0x1FC00010         /* L1DM Data Memory CPLB Default Settings Register */
#define DPERR_STAT             0x1FC00014         /* L1DM Data Memory Parity Error Status Register */
#define DCPLB_ADDR0            0x1FC00100         /* L1DM Data Memory CPLB Address Registers */
#define DCPLB_ADDR1            0x1FC00104         /* L1DM Data Memory CPLB Address Registers */
#define DCPLB_ADDR2            0x1FC00108         /* L1DM Data Memory CPLB Address Registers */
#define DCPLB_ADDR3            0x1FC0010C         /* L1DM Data Memory CPLB Address Registers */
#define DCPLB_ADDR4            0x1FC00110         /* L1DM Data Memory CPLB Address Registers */
#define DCPLB_ADDR5            0x1FC00114         /* L1DM Data Memory CPLB Address Registers */
#define DCPLB_ADDR6            0x1FC00118         /* L1DM Data Memory CPLB Address Registers */
#define DCPLB_ADDR7            0x1FC0011C         /* L1DM Data Memory CPLB Address Registers */
#define DCPLB_ADDR8            0x1FC00120         /* L1DM Data Memory CPLB Address Registers */
#define DCPLB_ADDR9            0x1FC00124         /* L1DM Data Memory CPLB Address Registers */
#define DCPLB_ADDR10           0x1FC00128         /* L1DM Data Memory CPLB Address Registers */
#define DCPLB_ADDR11           0x1FC0012C         /* L1DM Data Memory CPLB Address Registers */
#define DCPLB_ADDR12           0x1FC00130         /* L1DM Data Memory CPLB Address Registers */
#define DCPLB_ADDR13           0x1FC00134         /* L1DM Data Memory CPLB Address Registers */
#define DCPLB_ADDR14           0x1FC00138         /* L1DM Data Memory CPLB Address Registers */
#define DCPLB_ADDR15           0x1FC0013C         /* L1DM Data Memory CPLB Address Registers */
#define DCPLB_DATA0            0x1FC00200         /* L1DM Data Memory CPLB Data Registers */
#define DCPLB_DATA1            0x1FC00204         /* L1DM Data Memory CPLB Data Registers */
#define DCPLB_DATA2            0x1FC00208         /* L1DM Data Memory CPLB Data Registers */
#define DCPLB_DATA3            0x1FC0020C         /* L1DM Data Memory CPLB Data Registers */
#define DCPLB_DATA4            0x1FC00210         /* L1DM Data Memory CPLB Data Registers */
#define DCPLB_DATA5            0x1FC00214         /* L1DM Data Memory CPLB Data Registers */
#define DCPLB_DATA6            0x1FC00218         /* L1DM Data Memory CPLB Data Registers */
#define DCPLB_DATA7            0x1FC0021C         /* L1DM Data Memory CPLB Data Registers */
#define DCPLB_DATA8            0x1FC00220         /* L1DM Data Memory CPLB Data Registers */
#define DCPLB_DATA9            0x1FC00224         /* L1DM Data Memory CPLB Data Registers */
#define DCPLB_DATA10           0x1FC00228         /* L1DM Data Memory CPLB Data Registers */
#define DCPLB_DATA11           0x1FC0022C         /* L1DM Data Memory CPLB Data Registers */
#define DCPLB_DATA12           0x1FC00230         /* L1DM Data Memory CPLB Data Registers */
#define DCPLB_DATA13           0x1FC00234         /* L1DM Data Memory CPLB Data Registers */
#define DCPLB_DATA14           0x1FC00238         /* L1DM Data Memory CPLB Data Registers */
#define DCPLB_DATA15           0x1FC0023C         /* L1DM Data Memory CPLB Data Registers */


#define IMEM_CONTROL           0x1FC01004         /* L1IM Instruction Memory Control Register */
#define IMEM_STAT              0x1FC01008         /* L1IM Instruction Memory CPLB Status Register */
#define CODE_FAULT_STATUS      0x1FC01008         /*     Older definition or alias of above */
#define ICPLB_FAULT_ADDR       0x1FC0100C         /* L1IM Instruction Memory CPLB Fault Address Register */
#define CODE_FAULT_ADDR        0x1FC0100C         /*     Older definition or alias of above */
#define ICPLB_DFLT             0x1FC01010         /* L1IM Instruction Memory CPLB Default Settings Register */
#define IPERR_STAT             0x1FC01014         /* L1IM Instruction Parity Error Status Register */
#define ICPLB_ADDR0            0x1FC01100         /* L1IM Instruction Memory CPLB Address Registers */
#define ICPLB_ADDR1            0x1FC01104         /* L1IM Instruction Memory CPLB Address Registers */
#define ICPLB_ADDR2            0x1FC01108         /* L1IM Instruction Memory CPLB Address Registers */
#define ICPLB_ADDR3            0x1FC0110C         /* L1IM Instruction Memory CPLB Address Registers */
#define ICPLB_ADDR4            0x1FC01110         /* L1IM Instruction Memory CPLB Address Registers */
#define ICPLB_ADDR5            0x1FC01114         /* L1IM Instruction Memory CPLB Address Registers */
#define ICPLB_ADDR6            0x1FC01118         /* L1IM Instruction Memory CPLB Address Registers */
#define ICPLB_ADDR7            0x1FC0111C         /* L1IM Instruction Memory CPLB Address Registers */
#define ICPLB_ADDR8            0x1FC01120         /* L1IM Instruction Memory CPLB Address Registers */
#define ICPLB_ADDR9            0x1FC01124         /* L1IM Instruction Memory CPLB Address Registers */
#define ICPLB_ADDR10           0x1FC01128         /* L1IM Instruction Memory CPLB Address Registers */
#define ICPLB_ADDR11           0x1FC0112C         /* L1IM Instruction Memory CPLB Address Registers */
#define ICPLB_ADDR12           0x1FC01130         /* L1IM Instruction Memory CPLB Address Registers */
#define ICPLB_ADDR13           0x1FC01134         /* L1IM Instruction Memory CPLB Address Registers */
#define ICPLB_ADDR14           0x1FC01138         /* L1IM Instruction Memory CPLB Address Registers */
#define ICPLB_ADDR15           0x1FC0113C         /* L1IM Instruction Memory CPLB Address Registers */
#define ICPLB_DATA0            0x1FC01200         /* L1IM Instruction Memory CPLB Data Registers */
#define ICPLB_DATA1            0x1FC01204         /* L1IM Instruction Memory CPLB Data Registers */
#define ICPLB_DATA2            0x1FC01208         /* L1IM Instruction Memory CPLB Data Registers */
#define ICPLB_DATA3            0x1FC0120C         /* L1IM Instruction Memory CPLB Data Registers */
#define ICPLB_DATA4            0x1FC01210         /* L1IM Instruction Memory CPLB Data Registers */
#define ICPLB_DATA5            0x1FC01214         /* L1IM Instruction Memory CPLB Data Registers */
#define ICPLB_DATA6            0x1FC01218         /* L1IM Instruction Memory CPLB Data Registers */
#define ICPLB_DATA7            0x1FC0121C         /* L1IM Instruction Memory CPLB Data Registers */
#define ICPLB_DATA8            0x1FC01220         /* L1IM Instruction Memory CPLB Data Registers */
#define ICPLB_DATA9            0x1FC01224         /* L1IM Instruction Memory CPLB Data Registers */
#define ICPLB_DATA10           0x1FC01228         /* L1IM Instruction Memory CPLB Data Registers */
#define ICPLB_DATA11           0x1FC0122C         /* L1IM Instruction Memory CPLB Data Registers */
#define ICPLB_DATA12           0x1FC01230         /* L1IM Instruction Memory CPLB Data Registers */
#define ICPLB_DATA13           0x1FC01234         /* L1IM Instruction Memory CPLB Data Registers */
#define ICPLB_DATA14           0x1FC01238         /* L1IM Instruction Memory CPLB Data Registers */
#define ICPLB_DATA15           0x1FC0123C         /* L1IM Instruction Memory CPLB Data Registers */

#define EVT0                            0x1FC02000         /* Event Vector Table Registers */
#define EVT1                            0x1FC02004         /* Event Vector Table Registers */
#define EVT2                            0x1FC02008         /* Event Vector Table Registers */
#define EVT3                            0x1FC0200C         /* Event Vector Table Registers */
#define EVT4                            0x1FC02010         /* Event Vector Table Registers */
#define EVT5                            0x1FC02014         /* Event Vector Table Registers */
#define EVT6                            0x1FC02018         /* Event Vector Table Registers */
#define EVT7                            0x1FC0201C         /* Event Vector Table Registers */
#define EVT8                            0x1FC02020         /* Event Vector Table Registers */
#define EVT9                            0x1FC02024         /* Event Vector Table Registers */
#define EVT10                           0x1FC02028         /* Event Vector Table Registers */
#define EVT11                           0x1FC0202C         /* Event Vector Table Registers */
#define EVT12                           0x1FC02030         /* Event Vector Table Registers */
#define EVT13                           0x1FC02034         /* Event Vector Table Registers */
#define EVT14                           0x1FC02038         /* Event Vector Table Registers */
#define EVT15                           0x1FC0203C         /* Event Vector Table Registers */
#define EVT_OVERRIDE                    0x1FC02100         /* Event Vector Table Override Register */
#define IMASK                           0x1FC02104         /* Interrupt Mask Register */
#define IPEND                           0x1FC02108         /* Interrupt Pending Register */
#define ILAT                            0x1FC0210C         /* Interrupt Latch Register */
#define REG_ICU_CID                     0x1FC02114         /* ICU Context ID Register */
#define CEC_SID                         0x1FC02118         /* System ID Register */


#define TCNTL                           0x1FC03000         /* Timer Control Register */
#define TPERIOD                         0x1FC03004         /* Timer Period Register */
#define TSCALE                          0x1FC03008         /* Timer Scale Register */
#define TCOUNT                          0x1FC0300C         /* Timer Count Register */


#define DSPID                           0x1FC05000         /* DSP Identification Register */

#define WPIACTL                         0x1FC07000         /* Watchpoint Instruction Address Control Register 01 */
#define WPIA0                           0x1FC07040         /* Watchpoint Instruction Address Register */
#define WPIA1                           0x1FC07044         /* Watchpoint Instruction Address Register */
#define WPIA2                           0x1FC07048         /* Watchpoint Instruction Address Register */
#define WPIA3                           0x1FC0704C         /* Watchpoint Instruction Address Register */
#define WPIA4                           0x1FC07050         /* Watchpoint Instruction Address Register */
#define WPIA5                           0x1FC07054         /* Watchpoint Instruction Address Register */
#define WPIACNT0                        0x1FC07080         /* Watchpoint Instruction Address Count Register */
#define WPIACNT1                        0x1FC07084         /* Watchpoint Instruction Address Count Register */
#define WPIACNT2                        0x1FC07088         /* Watchpoint Instruction Address Count Register */
#define WPIACNT3                        0x1FC0708C         /* Watchpoint Instruction Address Count Register */
#define WPIACNT4                        0x1FC07090         /* Watchpoint Instruction Address Count Register */
#define WPIACNT5                        0x1FC07094         /* Watchpoint Instruction Address Count Register */
#define WPDACTL                         0x1FC07100         /* Watchpoint Data Address Control Register */
#define WPDA0                           0x1FC07140         /* Watchpoint Data Address Register */
#define WPDA1                           0x1FC07144         /* Watchpoint Data Address Register */
#define WPDACNT0                        0x1FC07180         /* Watchpoint Data Address Count Value Register */
#define WPDACNT1                        0x1FC07184         /* Watchpoint Data Address Count Value Register */
#define WPSTAT                          0x1FC07200         /* Watchpoint Status Register */

#define PFCTL                           0x1FC08000         /* Control Register */
#define PFCNTR0                         0x1FC08100         /* Counter 0 Register */
#define PFCNTR1                         0x1FC08104         /* Counter 1 Register */

#endif /* __BFIN_DEF_ADSP_EDN_core__ */
