#
# U-boot - Makefile
#
# Copyright (c) 2005-2008 Analog Device Inc.
#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#
# ADSP-BF70x fix by DAB-Embedded, 2014 (www.dab-embedded.com)
#

obj-y	:= bf707-ezkit.o
obj-$(CONFIG_BFIN_SOFT_SWITCH)   += soft_switch.o
