/* DO NOT EDIT THIS FILE
 * Automatically generated by generate-def-headers.xsl
 * DO NOT EDIT THIS FILE
 */

#ifndef __BFIN_DEF_ADSP_BF707_proc__
#define __BFIN_DEF_ADSP_BF707_proc__

#include "../mach-common/ADSP-EDN-core_def.h"

/* =========================
        MSI0
   ========================= */
#define MSI0_CTL                    0x20076000         /* MSI0 Contorl register */
#define MSI0_PWREN                  0x20076004         /* MSI0 Power Enable Register */
#define MSI0_CLKDIV                 0x20076008         /* MSI0 Clock Divider Register */
#define MSI0_CLKEN                  0x20076010         /* MSI0 Clock Enable Register */
#define MSI0_TMOUT                  0x20076014         /* MSI0 Timeout Register */
#define MSI0_CTYPE                  0x20076018         /* MSI0 Card Type Register */
#define MSI0_BLKSIZ                 0x2007601C         /* MSI0 Block Size Register */
#define MSI0_BYTCNT                 0x20076020         /* MSI0 Byte Count Register */
#define MSI0_IMSK                   0x20076024         /* MSI0 Interrupt Mask Register */
#define MSI0_CMDARG                 0x20076028         /* MSI0 Command Argument Register */
#define MSI0_CMD                    0x2007602C         /* MSI0 Command Register */
#define MSI0_RESP0                  0x20076030         /* MSI0 Response Register 0 */
#define MSI0_RESP1                  0x20076034         /* MSI0 Response Register 1 */
#define MSI0_RESP2                  0x20076038         /* MSI0 Response Register 2 */
#define MSI0_RESP3                  0x2007603C         /* MSI0 Response Register 3 */
#define MSI0_MSKISTAT               0x20076040         /* MSI0 Masked Interrupt Status Register */
#define MSI0_ISTAT                  0x20076044         /* MSI0 Raw Interrupt Status Register */
#define MSI0_STAT                   0x20076048         /* MSI0 Status Register */
#define MSI0_FIFOTH                 0x2007604C         /* MSI0 FIFO Threshold Watermark Register */
#define MSI0_CDETECT                0x20076050         /* MSI0 Card Detect Register */
#define MSI0_TCBCNT                 0x2007605C         /* MSI0 Transferred CIU Card Byte Count Register */
#define MSI0_TBBCNT                 0x20076060         /* MSI0 Transferred Host to BIU-FIFO Byte Count Register */
#define MSI0_DEBNCE                 0x20076064         /* MSI0 Debounce Count Register */
#define MSI0_USRID                  0x20076068         /* MSI0 User ID Register */
#define MSI0_VERID                  0x2007606C         /* MSI0 Version ID Register */
#define MSI0_HWCFG                  0x20076070         /* MSI0 Hardware Configuration Register */
#define MSI0_BUSMODE                0x20076080         /* MSI0 Bus Mode Register */
#define MSI0_PLDMND                 0x20076084         /* MSI0 Poll Demand Register */
#define MSI0_DBADDR                 0x20076088         /* MSI0 Descriptor List Base Address Register */
#define MSI0_IDSTS                  0x2007608C         /* MSI0 Internal DMA Status Register */
#define MSI0_IDINTEN                0x20076090         /* MSI0 Internal DMA Interrupt Enable Register */
#define MSI0_DSCADDR                0x20076094         /* MSI0 Current Host Descriptor Address Register */
#define MSI0_BUFADDR                0x20076098         /* MSI0 Current Buffer Descriptor Address Register */
#define MSI0_CDTHRCTL               0x20076100         /* MSI0 Card Threshold Control Register */
#define MSI0_ENSHIFT                0x20076110         /* MSI0 Register to control the amount of shift on enables */

#define TWI0_CLKDIV                 0x2004A000         /* TWI0 SCL Clock Divider */

/* ==================================================
        UART Registers
   ================================================== */

/* =========================
        UART0
   ========================= */
#define UART0_REVID                 0x2005F000         /* UART0 RevID */
#define UART0_CTL                   0x2005F004         /* UART0 Control Register */
#define UART0_STAT                  0x2005F008         /* UART0 Status Register */
#define UART0_SCR                   0x2005F00C         /* UART0 Scratch Register */
#define UART0_CLK                   0x2005F010         /* UART0 Clock Rate Register */
#define UART0_IMSK                  0x2005F014         /* UART0 Interrupt Mask Register */
#define UART0_IMSK_SET              0x2005F018         /* UART0 Interrupt Mask Set Register */
#define UART0_IMSK_CLR              0x2005F01C         /* UART0 Interrupt Mask Clear Register */
#define UART0_RBR                   0x2005F020         /* UART0 Receive Buffer Register */
#define UART0_THR                   0x2005F024         /* UART0 Transmit Hold Register */
#define UART0_TAIP                  0x2005F028         /* UART0 Transmit Address/Insert Pulse Register */
#define UART0_TSR                   0x2005F02C         /* UART0 Transmit Shift Register */
#define UART0_RSR                   0x2005F030         /* UART0 Receive Shift Register */
#define UART0_TXCNT                 0x2005F034         /* UART0 Transmit Counter Register */
#define UART0_RXCNT                 0x2005F038         /* UART0 Receive Counter Register */

/* =========================
        UART1
   ========================= */
#define UART1_REVID                 0x2005F400         /* UART1 RevID */
#define UART1_CTL                   0x2005F404         /* UART1 Control Register */
#define UART1_STAT                  0x2005F408         /* UART1 Status Register */
#define UART1_SCR                   0x2005F40C         /* UART1 Scratch Register */
#define UART1_CLK                   0x2005F410         /* UART1 Clock Rate Register */
#define UART1_IMSK                  0x2005F414         /* UART1 Interrupt Mask Register */
#define UART1_IMSK_SET              0x2005F418         /* UART1 Interrupt Mask Set Register */
#define UART1_IMSK_CLR              0x2005F41C         /* UART1 Interrupt Mask Clear Register */
#define UART1_RBR                   0x2005F420         /* UART1 Receive Buffer Register */
#define UART1_THR                   0x2005F424         /* UART1 Transmit Hold Register */
#define UART1_TAIP                  0x2005F428         /* UART1 Transmit Address/Insert Pulse Register */
#define UART1_TSR                   0x2005F42C         /* UART1 Transmit Shift Register */
#define UART1_RSR                   0x2005F430         /* UART1 Receive Shift Register */
#define UART1_TXCNT                 0x2005F434         /* UART1 Transmit Counter Register */
#define UART1_RXCNT                 0x2005F438         /* UART1 Receive Counter Register */

/* =========================
        PORTA
   ========================= */
#define PORTA_FER                   0x20040000         /* PORTA Port x Function Enable Register */
#define PORTA_FER_SET               0x20040004         /* PORTA Port x Function Enable Set Register */
#define PORTA_FER_CLR               0x20040008         /* PORTA Port x Function Enable Clear Register */
#define PORTA_DATA                  0x2004000C         /* PORTA Port x GPIO Data Register */
#define PORTA_DATA_SET              0x20040010         /* PORTA Port x GPIO Data Set Register */
#define PORTA_DATA_CLR              0x20040014         /* PORTA Port x GPIO Data Clear Register */
#define PORTA_DIR                   0x20040018         /* PORTA Port x GPIO Direction Register */
#define PORTA_DIR_SET               0x2004001C         /* PORTA Port x GPIO Direction Set Register */
#define PORTA_DIR_CLR               0x20040020         /* PORTA Port x GPIO Direction Clear Register */
#define PORTA_INEN                  0x20040024         /* PORTA Port x GPIO Input Enable Register */
#define PORTA_INEN_SET              0x20040028         /* PORTA Port x GPIO Input Enable Set Register */
#define PORTA_INEN_CLR              0x2004002C         /* PORTA Port x GPIO Input Enable Clear Register */
#define PORTA_MUX                   0x20040030         /* PORTA Port x Multiplexer Control Register */
#define PORTA_DATA_TGL              0x20040034         /* PORTA Port x GPIO Input Enable Toggle Register */
#define PORTA_POL                   0x20040038         /* PORTA Port x GPIO Polarity Invert Register */
#define PORTA_POL_SET               0x2004003C         /* PORTA Port x GPIO Polarity Invert Set Register */
#define PORTA_POL_CLR               0x20040040         /* PORTA Port x GPIO Polarity Invert Clear Register */
#define PORTA_LOCK                  0x20040044         /* PORTA Port x GPIO Lock Register */
#define PORTA_TRIG_TGL              0x20040048         /* PORTA Port x GPIO Trigger Toggle Register */

/* =========================
        PORTB
   ========================= */
#define PORTB_FER                   0x20040080         /* PORTB Port x Function Enable Register */
#define PORTB_FER_SET               0x20040084         /* PORTB Port x Function Enable Set Register */
#define PORTB_FER_CLR               0x20040088         /* PORTB Port x Function Enable Clear Register */
#define PORTB_DATA                  0x2004008C         /* PORTB Port x GPIO Data Register */
#define PORTB_DATA_SET              0x20040090         /* PORTB Port x GPIO Data Set Register */
#define PORTB_DATA_CLR              0x20040094         /* PORTB Port x GPIO Data Clear Register */
#define PORTB_DIR                   0x20040098         /* PORTB Port x GPIO Direction Register */
#define PORTB_DIR_SET               0x2004009C         /* PORTB Port x GPIO Direction Set Register */
#define PORTB_DIR_CLR               0x200400A0         /* PORTB Port x GPIO Direction Clear Register */
#define PORTB_INEN                  0x200400A4         /* PORTB Port x GPIO Input Enable Register */
#define PORTB_INEN_SET              0x200400A8         /* PORTB Port x GPIO Input Enable Set Register */
#define PORTB_INEN_CLR              0x200400AC         /* PORTB Port x GPIO Input Enable Clear Register */
#define PORTB_MUX                   0x200400B0         /* PORTB Port x Multiplexer Control Register */
#define PORTB_DATA_TGL              0x200400B4         /* PORTB Port x GPIO Input Enable Toggle Register */
#define PORTB_POL                   0x200400B8         /* PORTB Port x GPIO Polarity Invert Register */
#define PORTB_POL_SET               0x200400BC         /* PORTB Port x GPIO Polarity Invert Set Register */
#define PORTB_POL_CLR               0x200400C0         /* PORTB Port x GPIO Polarity Invert Clear Register */
#define PORTB_LOCK                  0x200400C4         /* PORTB Port x GPIO Lock Register */
#define PORTB_TRIG_TGL              0x200400C8         /* PORTB Port x GPIO Trigger Toggle Register */

/* =========================
        PORTC
   ========================= */
#define PORTC_FER                   0x20040100         /* PORTC Port x Function Enable Register */
#define PORTC_FER_SET               0x20040104         /* PORTC Port x Function Enable Set Register */
#define PORTC_FER_CLR               0x20040108         /* PORTC Port x Function Enable Clear Register */
#define PORTC_DATA                  0x2004010C         /* PORTC Port x GPIO Data Register */
#define PORTC_DATA_SET              0x20040110         /* PORTC Port x GPIO Data Set Register */
#define PORTC_DATA_CLR              0x20040114         /* PORTC Port x GPIO Data Clear Register */
#define PORTC_DIR                   0x20040118         /* PORTC Port x GPIO Direction Register */
#define PORTC_DIR_SET               0x2004011C         /* PORTC Port x GPIO Direction Set Register */
#define PORTC_DIR_CLR               0x20040120         /* PORTC Port x GPIO Direction Clear Register */
#define PORTC_INEN                  0x20040124         /* PORTC Port x GPIO Input Enable Register */
#define PORTC_INEN_SET              0x20040128         /* PORTC Port x GPIO Input Enable Set Register */
#define PORTC_INEN_CLR              0x2004012C         /* PORTC Port x GPIO Input Enable Clear Register */
#define PORTC_MUX                   0x20040130         /* PORTC Port x Multiplexer Control Register */
#define PORTC_DATA_TGL              0x20040134         /* PORTC Port x GPIO Input Enable Toggle Register */
#define PORTC_POL                   0x20040138         /* PORTC Port x GPIO Polarity Invert Register */
#define PORTC_POL_SET               0x2004013C         /* PORTC Port x GPIO Polarity Invert Set Register */
#define PORTC_POL_CLR               0x20040140         /* PORTC Port x GPIO Polarity Invert Clear Register */
#define PORTC_LOCK                  0x20040144         /* PORTC Port x GPIO Lock Register */
#define PORTC_TRIG_TGL              0x20040148         /* PORTC Port x GPIO Trigger Toggle Register */


/* =========================
        SMC0
   ========================= */
#define SMC_B0CTL                  0x2005D00C         /* SMC0 Bank 0 Control Register */
#define SMC_B0TIM                  0x2005D010         /* SMC0 Bank 0 Timing Register */
#define SMC_B0ETIM                 0x2005D014         /* SMC0 Bank 0 Extended Timing Register */
#define SMC_B1CTL                  0x2005D01C         /* SMC0 Bank 1 Control Register */
#define SMC_B1TIM                  0x2005D020         /* SMC0 Bank 1 Timing Register */
#define SMC_B1ETIM                 0x2005D024         /* SMC0 Bank 1 Extended Timing Register */
#define SMC_B2CTL                  0x2005D02C         /* SMC0 Bank 2 Control Register */
#define SMC_B2TIM                  0x2005D030         /* SMC0 Bank 2 Timing Register */
#define SMC_B2ETIM                 0x2005D034         /* SMC0 Bank 2 Extended Timing Register */
#define SMC_B3CTL                  0x2005D03C         /* SMC0 Bank 3 Control Register */
#define SMC_B3TIM                  0x2005D040         /* SMC0 Bank 3 Timing Register */
#define SMC_B3ETIM                 0x2005D044         /* SMC0 Bank 3 Extended Timing Register */


/* =========================
        WDOG0
   ========================= */
#define WDOG_CTL                   0x20046000         /* WDOG0 Control Register */
#define WDOG_CNT                   0x20046004         /* WDOG0 Count Register */
#define WDOG_STAT                  0x20046008         /* WDOG0 Watchdog Timer Status Register */


#define SPI0_REGBASE      0x20055000 /* SPI0 Base Address */
#define SPI1_REGBASE      0x20056000 /* SPI1 Base Address */
#define SPI2_REGBASE      0x20057000 /* SPI2 Base Address */

/* =========================
        DMA10
   ========================= */
#define DMA10_DSCPTR_NXT            0x20086000         /* DMA10 Pointer to Next Initial Descriptor */
#define DMA10_ADDRSTART             0x20086004         /* DMA10 Start Address of Current Buffer */
#define DMA10_CFG                   0x20086008         /* DMA10 Configuration Register */
#define DMA10_XCNT                  0x2008600C         /* DMA10 Inner Loop Count Start Value */
#define DMA10_XMOD                  0x20086010         /* DMA10 Inner Loop Address Increment */
#define DMA10_YCNT                  0x20086014         /* DMA10 Outer Loop Count Start Value (2D only) */
#define DMA10_YMOD                  0x20086018         /* DMA10 Outer Loop Address Increment (2D only) */
#define DMA10_DSCPTR_CUR            0x20086024         /* DMA10 Current Descriptor Pointer */
#define DMA10_DSCPTR_PRV            0x20086028         /* DMA10 Previous Initial Descriptor Pointer */
#define DMA10_ADDR_CUR              0x2008602C         /* DMA10 Current Address */
#define DMA10_STAT                  0x20086030         /* DMA10 Status Register */
#define DMA10_XCNT_CUR              0x20086034         /* DMA10 Current Count(1D) or intra-row XCNT (2D) */
#define DMA10_YCNT_CUR              0x20086038         /* DMA10 Current Row Count (2D only) */

#define MDMA_S0_NEXT_DESC_PTR DMA16_DSCPTR_NXT
#define DMA16_DSCPTR_NXT  0x2008C000 /* DMA16 Pointer to Next Initial Desc */
#define MDMA_D0_NEXT_DESC_PTR DMA17_DSCPTR_NXT
#define DMA17_DSCPTR_NXT  0x2008D000 /* DMA17 Pointer to Next Initial Desc */

/* =========================
        DMC0
   ========================= */
#define DMC0_CTL                    0x200C0004         /* DMC0 Control Register */
#define DMC0_STAT                   0x200C0008         /* DMC0 Status Register */
#define DMC0_EFFCTL                 0x200C000C         /* DMC0 Efficiency Control Register */
#define DMC0_PRIO                   0x200C0010         /* DMC0 Priority ID Register 1 */
#define DMC0_PRIOMSK                0x200C0014         /* DMC0 Priority ID Mask Register 1 */
#define DMC0_PRIO2                  0x200C0018         /* DMC0 Priority ID Register 2 */
#define DMC0_PRIOMSK2               0x200C001C         /* DMC0 Priority ID Mask Register 2 */
#define DMC0_CFG                    0x200C0040         /* DMC0 Configuration Register */
#define DMC0_TR0                    0x200C0044         /* DMC0 Timing 0 Register */
#define DMC0_TR1                    0x200C0048         /* DMC0 Timing 1 Register */
#define DMC0_TR2                    0x200C004C         /* DMC0 Timing 2 Register */
#define DMC0_MSK                    0x200C005C         /* DMC0 Mask (Mode Register Shadow) Register */
#define DMC0_MR                     0x200C0060         /* DMC0 Shadow MR Register */
#define DMC0_EMR1                   0x200C0064         /* DMC0 Shadow EMR1 Register */
#define DMC0_EMR2                   0x200C0068         /* DMC0 Shadow EMR2 Register */
#define DMC0_DLLCTL                 0x200C0080         /* DMC0 DLL Control Register */
#define DMC0_RDDATABUFID1           0x200C0100         /* DMC0 DMC Read Data Buffer ID register 1 */
#define DMC0_RDDATABUFMSK1          0x200C0104         /* DMC0 DMC Read Data Buffer Mask Register 1 */
#define DMC0_RDDATABUFID2           0x200C0108         /* DMC0 DMC Read Data Buffer ID register 2 */
#define DMC0_RDDATABUFMSK2          0x200C010C         /* DMC0 DMC Read Data Buffer Mask Register 2 */
#define DMC0_PHY_CTL0               0x200C1000         /* DMC0 PHY Control 0 Register */
#define DMC0_PHY_CTL2               0x200C1008         /* DMC0 PHY Control 2 Register */
#define DMC0_PHY_CTL4               0x200C1010         /* DMC0 PHY Control 4 Register */
#define DMC0_PHY_STAT0              0x200C101C         /* DMC0 PHY Status 0 Register */
#define DMC0_CAL_PADCTL0            0x200C1034         /* DMC0 CALIBRATION PAD CTL 0 Register */
#define DMC0_CAL_PADCTL1            0x200C1038         /* DMC0 CALIBRATION PAD CTL1 Register */
#define DMC0_CAL_PADCTL2            0x200C103C         /* DMC0 CALIBRATION PAD CTL2 Register */

#define SEC0_CCTL0        0x20004400 /* SEC0 Core Control Register n */
#define SEC0_FCTL         0x20004010 /* SEC0 Fault Control Register */
#define SEC0_GCTL         0x20004000 /* SEC0 Global Control Register */
#define SEC0_SCTL0        0x20004800 /* SEC0 IRQ Source Control Register n */

/* =========================
        RCU0
   ========================= */
#define RCU0_CTL                    0x20000000         /* RCU0 Control Register */
#define RCU0_STAT                   0x20000004         /* RCU0 Status Register */
#define RCU0_CRCTL                  0x20000008         /* RCU0 Core Reset Control Register */
#define RCU0_CRSTAT                 0x2000000C         /* RCU0 Core Reset Status Register */
#define RCU0_SIDIS                  0x20000010         /* RCU0 System Interface Disable Register */
#define RCU0_SISTAT                 0x20000014         /* RCU0 System Interface Status Register */
#define RCU0_SVECT_LCK              0x20000018         /* RCU0 SVECT Lock Register */
#define RCU0_BCODE                  0x2000001C         /* RCU0 Boot Code Register */
#define RCU0_SVECT0                 0x20000020         /* RCU0 Software Vector Register 0 */
#define RCU0_MSG                    0x20000060         /* RCU0 Message Register */
#define RCU0_MSG_SET                0x20000064         /* RCU0 Message Set Bits Register */
#define RCU0_MSG_CLR                0x20000068         /* RCU0 Message Clear Bits Register */
#define RCU0_REVID                  0x20000070         /* RCU0 Revision ID Register */

/* =========================
        CGU0
   ========================= */
#define CGU_CTL                    0x20002000         /* CGU0 Control Register */
#define CGU_PLLCTL                 0x20002004         /* CGU0 PLL Control Register */
#define CGU_STAT                   0x20002008         /* CGU0 Status Register */
#define CGU_DIV                    0x2000200C         /* CGU0 Clocks Divisor Register */
#define CGU_CLKOUTSEL              0x20002010         /* CGU0 CLKOUT Select Register */
#define CGU_TSCTL                  0x20002018         /* CGU0 Timestamp Control Register */
#define CGU_TSVALUE0               0x2000201C         /* CGU0 Timestamp Counter Initial 32 LSB Value Register */
#define CGU_TSVALUE1               0x20002020         /* CGU0 Timestamp Counter Initial MSB Value Register */
#define CGU_TSCOUNT0               0x20002024         /* CGU0 Timestamp Counter 32 LSB */
#define CGU_TSCOUNT1               0x20002028         /* CGU0 Timestamp Counter 32 MSB Register */
#define CGU_CCBF_DIS               0x2000202C         /* CGU0 Core Clock Buffer Disable Register */
#define CGU_CCBF_STAT              0x20002030         /* CGU0 Core Clock Buffer Status Register */
#define CGU_SCBF_DIS               0x20002038         /* CGU0 System Clock Buffer Disable Register */
#define CGU_SCBF_STAT              0x2000203C         /* CGU0 System Clock Buffer Status Register */
#define CGU_REVID                  0x20002048         /* CGU0 Revision ID Register */

/* =========================
        DPM0
   ========================= */
#define DPM0_CTL                    0x20003000         /* DPM0 Control Register */
#define DPM0_STAT                   0x20003004         /* DPM0 Status Register */
#define DPM0_WAKE_EN                0x2000301C         /* DPM0 Wakeup Enable Register */
#define DPM0_WAKE_POL               0x20003020         /* DPM0 Wakeup Polarity Register */
#define DPM0_WAKE_STAT              0x20003024         /* DPM0 Wakeup Status Register */
#define DPM0_HIB_DIS                0x20003028         /* DPM0 Hibernate Disable Register */
#define DPM0_PGCNTR                 0x2000302C         /* DPM0 Power Good Counter Register */
#define DPM0_RESTORE0               0x20003030         /* DPM0 Restore Registers */
#define DPM0_RESTORE1               0x20003034         /* DPM0 Restore Registers */
#define DPM0_RESTORE2               0x20003038         /* DPM0 Restore Registers */
#define DPM0_RESTORE3               0x2000303C         /* DPM0 Restore Registers */
#define DPM0_RESTORE4               0x20003040         /* DPM0 Restore Registers */
#define DPM0_RESTORE5               0x20003044         /* DPM0 Restore Registers */
#define DPM0_RESTORE6               0x20003048         /* DPM0 Restore Registers */
#define DPM0_RESTORE7               0x2000304C         /* DPM0 Restore Registers */
#define DPM0_RESTORE8               0x20003050         /* DPM0 Restore Registers */
#define DPM0_RESTORE9               0x20003054         /* DPM0 Restore Registers */
#define DPM0_RESTORE10              0x20003058         /* DPM0 Restore Registers */
#define DPM0_RESTORE11              0x2000305C         /* DPM0 Restore Registers */
#define DPM0_RESTORE12              0x20003060         /* DPM0 Restore Registers */
#define DPM0_RESTORE13              0x20003064         /* DPM0 Restore Registers */
#define DPM0_RESTORE14              0x20003068         /* DPM0 Restore Registers */
#define DPM0_RESTORE15              0x2000306C         /* DPM0 Restore Registers */
#define DPM0_REVID                  0x20003084         /* DPM0 Revision ID */


#define USB_FADDR         0x200D0000 /* USB Device Address in Peripheral Mode*/
#define USB_DMA_IRQ       0x200D0200 /* USB Interrupt Register */
#define USB_VBUS_CTL      0x200D0380 /* USB VBus Control */
#define USB_PHY_CTL       0x200D0394 /* USB PHY Control */
#define USB_PLL_OSC       0x200D0398 /* USB PLL and Oscillator Control */


#define                           CHIPID  0x20000014
/* CHIPID Masks */
#define                   CHIPID_VERSION  0xF0000000
#define                    CHIPID_FAMILY  0x0FFFF000
#define               CHIPID_MANUFACTURE  0x00000FFE

#define L1_DATA_A_SRAM 0x11800000 /* Data Bank A SRAM */
#define L1_DATA_A_SRAM_SIZE 0x8000
#define L1_DATA_A_SRAM_END (L1_DATA_A_SRAM + L1_DATA_A_SRAM_SIZE)
#define L1_DATA_B_SRAM 0x11900000 /* Data Bank B SRAM */
#define L1_DATA_B_SRAM_SIZE 0x4000
#define L1_DATA_B_SRAM_END (L1_DATA_B_SRAM + L1_DATA_B_SRAM_SIZE)

#define L1_INST_SRAM 0x11A00000 /* Inst Bank A SRAM */
#define L1_INST_SRAM_SIZE 0xC000
#define L1_INST_SRAM_END (L1_INST_SRAM + L1_INST_SRAM_SIZE)

#endif /* __BFIN_DEF_ADSP_BF707_proc__ */
